### ISSUE TITLE
May not contain more than 1 protocol when type is 'LoadBalancer' (mixed protocols error) AWS EKS

### ISSUE THREAD

**Issue by kseniyashaydurova** [jitsi-contrib/jitsi-helm#50]
With a new `jitsi-helm` version `1.2.2` we started experiencing below issue in AWS EKS `v1.21.5-eks-bc4871b`:

`one or more objects failed to apply, reason: Service "vp-jitsi-meet-jvb" is invalid: spec.ports: Invalid value: []core.ServicePort{core.ServicePort{Name:"rtp-udp", Protocol:"UDP", AppProtocol:(*string)(nil), Port:31000, TargetPort:intstr.IntOrString{Type:0, IntVal:31000, StrVal:""}, NodePort:31000}, core.ServicePort{Name:"colibri-ws-tcp", Protocol:"TCP", AppProtocol:(*string)(nil), Port:9090, TargetPort:intstr.IntOrString{Type:0, IntVal:9090, StrVal:""}, NodePort:0}}: may not contain more than 1 protocol when type is 'LoadBalancer'`

This error says that we are not allowed to create LoadBalancer services with mixed protocols (UDP and TCP). As current workaround we just forked your repository and removed this part from JVB service template:
https://github.com/jitsi-contrib/jitsi-helm/blob/main/templates/jvb/service.yaml#L24-L28

So we need `websockets` functionality, but have errors on JVB service creation because of `colibri-ws-tcp`. Can you please tell why this change was needed for `websockets`? What part `colibri-ws-tcp` is responsible for and will we get any issues because of turning it off? Thanks!

@dmitry-mightydevops

**Comment by spijet** [comment]
Hello @kseniyashaydurova!

Sorry for late reply. I suppose that we could split the service in two (one for UDP transport and one for Colibri WS endpoint). The Colibri WS port shouldn't be exposed to the outside world anyway and is only accessed by the `web` container, so it can be hardcoded to always be of `ClusterIP` type.

By removing the mentioned part from JVB service (and not adding it as a separate service) you cut off the ability for `web` container to reach the Colibri WS port, which breaks half of Jitsi Meet's WebSocket signalling functionality. You can work around this by turning off WebSocket support for Colibri (which is now the default since Chart version `v1.3.0`).
