### ISSUE TITLE
jigasi support

### ISSUE THREAD

**Issue by palmtown** [jitsi-contrib/jitsi-helm#73]
Hello community,

Does anyone know if jigasi is supported with this Kubernetes helm deployment?  I see it is supported with a docker installation at https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker/ however, no mentioning of it here.  

Thanks!

**Comment by spijet** [comment]
Hello @palmtown!

IIRC Jigasi is a SIP gateway, which makes it tricky to set up properly, let alone reliably use it in k8s environment. Because of this (and perceived lack of people insterested in connecting Jitsi Meet with telephony networks) we haven't really considered adding support for it in this chart, which is aimed to be as "plug-n-play" as possible.

**Comment by palmtown** [comment]
Hello @spijet ,

Thanks for the update.  Much appreciated!
