### ISSUE TITLE
Unable to use jitsi-helm v1.2.3

### ISSUE THREAD

**Issue by anirbandas18** [jitsi-contrib/jitsi-helm#79]
I am trying to install Jitsi using the jitsi-helm helm chart v1.2.3 through helmfile but I receive the following error when I try to template my helmfile with the jitsi-helm chart. Because of a requirement, I have to use jitsi-helm version < v1.2.3

`COMBINED OUTPUT:
  install.go:194: [debug] Original chart version: "1.2.3"
  install.go:211: [debug] CHART PATH: /Users/adas/Library/Caches/helm/repository/jitsi-meet-1.2.3.tgz
  Error: execution error at (jitsi-meet/templates/web/deployment.yaml:24:28): (web.resolverIP) Please set an IP address of your KubeDNS service!
  helm.go:84: [debug] execution error at (jitsi-meet/templates/web/deployment.yaml:24:28): (web.resolverIP) Please set an IP address of your KubeDNS service!`

Kindly help me in resolving this.

**Comment by spijet** [comment]
Hello @anirbandas18!

Sorry for the late reply. Can you please elaborate on why do you need to use the v1.2.3 specifically?

Older Jitsi Meet images (used in chart version v1.2.3) lacked a proper DNS detection mechanism suitable for Kubernetes environment and assumed they're running in Docker instead, which lead to buggy behaviour in `jitsi-web` container. The only proper solution to that problem was to require the user to set the IP address of the Kubernetes DNS service in chart values. You can find the IP address of your DNS service by running:
```
kubectl -n kube-system get svc | grep dns
```

Or you can run a newer chart version instead.

**Comment by anirbandas18** [comment]
Newer version of helm-chart fixes this
