### ISSUE TITLE
Why Exporter from systemli and not own?

### ISSUE THREAD

**Issue by genofire** [jitsi-contrib/jitsi-helm#95]
container from systemli:
https://github.com/systemli/prometheus-jitsi-meet-exporter

container jitsi-contrib:
https://github.com/jitsi-contrib/jitsi-exporter

**Comment by spijet** [comment]
Hello @genofire!

I don't remember all the details, but I think I chose the `systemli/` one because it gets updated more often and produces more useful metrics, and provides a ready-to-use Grafana dashboard as well. I'll compare them again and consider using the `jitsi-contrib/` one if it is good enough.

**Comment by genofire** [comment]
Oh, an grafana dashboard - could we but that as configmap into this helmchart ? So that the default sidecar of grafana could grab it?

**Comment by spijet** [comment]
Closing the issue, as we do have the proper dashboard embedded in the chart now.
